Traceback (most recent call last):
  File "/gpfs/data/fs72515/nadja_g/SimCLR/simclr.py", line 26, in <module>
    from skimage import io
ModuleNotFoundError: No module named 'skimage'
